version: '3'

services:

  app:
    build: .
    ports:
      - '8000:8000'
    networks:
      - local
    depends_on:
      - worker
    volumes:
      - './src:/src'
    env_file:
      - .env

  worker:
    build: .
    command: python worker.py
    networks:
      - local
    depends_on:
      - redis
    volumes:
      - './src:/src'
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - local



networks:
  local: